networks:
  AIservice:

services:
  frontend:
    build: front
    ports:
      - 8501:8501
    networks: 
      AIservice: 
        aliases: 
          - front.docker
    depends_on:
      - back
    volumes:
        - ./front:/app
        - ./storage:/storage

  backend:
    build: back
    ports:
      - 8000:8000
    networks: 
      AIservice: 
        aliases: 
          - back.docker
    volumes:
      - ./back:/app
      - ./storage:/storage
  
  # db:
  #   build: BDD
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: emotion_db 
  #     POSTGRES_USER: admin
  #   ports:
  #     - 8080:8080